### ISSUE TITLE
Unicode vs. bytes in Python 3.x

### ISSUE THREAD

**Issue by hosford42** [captin411/ofxclient#27]
I'm getting a TypeError when I try to list the accounts for my institution:

```python
*** Python 3.4.5 |Anaconda 2.1.0 (64-bit)| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)] on win32. ***

>>> institution.accounts()
Traceback (most recent call last):
  File "<string>", line 301, in runcode
  File "<interactive input>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\ofxclient\institution.py", line 143, in accounts
    parsed = OfxParser.parse(resp_handle)
  File "C:\Anaconda3\lib\site-packages\ofxparse\ofxparse.py", line 398, in parse
    ofx_file = OfxPreprocessedFile(file_handle)
  File "C:\Anaconda3\lib\site-packages\ofxparse\ofxparse.py", line 168, in __init__
    super(OfxPreprocessedFile, self).__init__(fh)
  File "C:\Anaconda3\lib\site-packages\ofxparse\ofxparse.py", line 98, in __init__
    self.read_headers()
  File "C:\Anaconda3\lib\site-packages\ofxparse\ofxparse.py", line 104, in read_headers
    head_data = head_data[:head_data.find(six.b('<'))]
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by sneilan** [comment]
I've ran into the same issue. Now trying in Python 2.7.

**Comment by cu** [comment]
Ran into this as well. Removing the call to `six.b()` fixed it, but kept tripping over further conversion/encoding errors.

**Comment by mattprompt** [comment]
The issue is that ofxparse expects a "seekable file-like byte stream object".
See line 87, https://github.com/jseutter/ofxparse/blob/master/ofxparse/ofxparse.py
Ofxclient is providing a StreamIO object to ofxparse [StreamIO.StreamIO for Python 2, IO.StreamIO for Python3]. 
Ofxparse is apparently happy with the Python 2 StreamIO.StreamIO object, but is not happy with the Python3 IO.StreamIO.
However converting the IO.StreamIO object to an IO.BytesIO object fixes the issue.
For example, account.py, line 112:
change:
`return OfxParser.parse(self.download(days=days))`
to:
`return OfxParser.parse(BytesIO(((self.download(days=days)).read()).encode()))`
seems to work for Python3, assuming IO.BytesIO is imported.
I'll fork and request pull in the next few days.

**Comment by mattprompt** [comment]
Pull request #30 submitted to resolve this issue.
