### ISSUE TITLE
NameError: global name 'ofx_version' is not defined

### ISSUE THREAD

**Issue by msewell13** [captin411/ofxclient#64]
I keep getting this name error when trying to add new accounts. It doesn't matter which bank, I get the same error on every one. I suppose this is some type of configuration error but can't figure it out.
I'm on a ubuntu machine, installed with apt-get and made sure I had all dependencies installed.

full traceback looks like this:
```
Traceback (most recent call last):
  File "/usr/bin/ofxclient", line 11, in <module>
    load_entry_point('ofxclient==2.0.2', 'console_scripts', 'ofxclient')()
  File "/usr/lib/python2.7/dist-packages/ofxclient/cli.py", line 63, in run
    main_menu(args)
  File "/usr/lib/python2.7/dist-packages/ofxclient/cli.py", line 83, in main_menu
    add_account_menu(args)
  File "/usr/lib/python2.7/dist-packages/ofxclient/cli.py", line 130, in add_account_menu
    if login_check_menu(bank, args):
  File "/usr/lib/python2.7/dist-packages/ofxclient/cli.py", line 209, in login_check_menu
    client_args={ofx_version: args.ofx_version}
NameError: global name 'ofx_version' is not defined
```

**Comment by egh** [comment]
I think the problem here may be that you need python3?

**Comment by ghost** [comment]
Same issue using Python3.
