### ISSUE TITLE
ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by TRSx80** [captin411/ofxclient#66]
I'm on Debian Stable. Installed latest by cloning directly from git. Everything seemed to go fine, until I tried to add my bank:

```
$ ofxclient

+----------------------------------
Main
Edit /home/trs80/ofxclient.ini to
change descriptions or ofx options
+----------------------------------
(A) Add an account
(Q) Quit
choice> a
+----------------------------------
Add account
+----------------------------------
------
Notice
------
You are about to search for bank connection information
on a third party website.  This means you are trusting
http://ofxhome.com and their security policies.

You will be sending your bank name to this website.
------
bank name eg. "express" (enter to exit)> My Bank
(0) My Bank
(1) My Bank Alternate Name
choice> 0
Traceback (most recent call last):
  File "/usr/local/bin/ofxclient", line 11, in <module>
    load_entry_point('ofxclient==2.0.4', 'console_scripts', 'ofxclient')()
  File "/usr/local/lib/python3.5/dist-packages/ofxclient-2.0.4-py3.5.egg/ofxclient/cli.py", line 63, in run
    main_menu(args)
  File "/usr/local/lib/python3.5/dist-packages/ofxclient-2.0.4-py3.5.egg/ofxclient/cli.py", line 83, in main_menu
    add_account_menu(args)
  File "/usr/local/lib/python3.5/dist-packages/ofxclient-2.0.4-py3.5.egg/ofxclient/cli.py", line 129, in add_account_menu
    bank = OFXHome.lookup(found[int(choice)]['id'])
  File "/usr/local/lib/python3.5/dist-packages/ofxhome-0.3.3-py3.5.egg/ofxhome/__init__.py", line 29, in lookup
  File "/usr/local/lib/python3.5/dist-packages/ofxhome-0.3.3-py3.5.egg/ofxhome/__init__.py", line 129, in __init__
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S'
```

**Comment by drbronner** [comment]
I'm having the same issue with a different bank, on macOS, using pip3. Were you ever able to resolve this?

**Comment by TRSx80** [comment]
@drbronner,

I don't think I was.

Right now I am wondering why I didn't try and set it up manually? It's been a while, and I might not be remembering correctly, but I think even if you could figure out your bank settings, the ofxclient I think has to run this to set it up. I don't believe I ever figured out any other way to enter it manually.

I sure wish I could though, as the manual nature of having to download stuff all the time from the bank is creating more friction than I would like.

**Comment by drbronner** [comment]
Cool thanks. If I get anywhere on this I'll post here.

**Comment by TRSx80** [comment]
At some point I took another look at this and got it working.  Then I forgot about this Issue (sorry about that).

The solution lies in [this unmerged PR](https://github.com/captin411/ofxclient/pull/61).  I don't actually even recall how I figured this out now (it has been a little while).  At any rate, I cloned that guy (terceiro)'s repository instead of this one, and then switched to that branch (`fix-configparser-usage`).

I vaguely remember having to do one other little thing, but because this has been a while now, I'll be damned if I can remember what that was at this point...  Again, sorry about that!  Maybe post back here how you are getting on and it might jog my memory.

I am leaving this open, as it's not really "fixed" until that PR gets merged in...
