### ISSUE TITLE
Error from configparser when setting up new computer

### ISSUE THREAD

**Issue by jgriffitts** [captin411/ofxclient#83]
Running ofxclient for the first time, setting up accounts. Computer is Windows 10 with 64-bit Python 3.7.6 installed via miniconda, and ofxclient 2.0.3 installed via pip.

After entering user/password for a bank, I got the following traceback:
```
password>
Traceback (most recent call last):
  File "c:\programdata\miniconda2\envs\py3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda2\envs\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda2\envs\py3\Scripts\ofxclient.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda2\envs\py3\lib\site-packages\ofxclient\cli.py", line 63, in run
    main_menu(args)
  File "c:\programdata\miniconda2\envs\py3\lib\site-packages\ofxclient\cli.py", line 83, in main_menu
    add_account_menu(args)
  File "c:\programdata\miniconda2\envs\py3\lib\site-packages\ofxclient\cli.py", line 130, in add_account_menu
    if login_check_menu(bank, args):
  File "c:\programdata\miniconda2\envs\py3\lib\site-packages\ofxclient\cli.py", line 219, in login_check_menu
    GlobalConfig.add_account(a)
  File "c:\programdata\miniconda2\envs\py3\lib\site-packages\ofxclient\config.py", line 244, in add_account
    self.parser.set(section_id, key, section_items[str(key)])   # JCG
  File "c:\programdata\miniconda2\envs\py3\lib\site-packages\ofxclient\config.py", line 122, in set
    ConfigParser.set(self, section, option, value)
  File "c:\programdata\miniconda2\envs\py3\lib\configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "c:\programdata\miniconda2\envs\py3\lib\configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

I don't really understand this bug, but found a brute-force fix, by changing line 244 in config.py:
was:
`self.parser.set(section_id, key, section_items[key])`
is:
`self.parser.set(section_id, key, str(section_items[key]))`

Everything seems to work OK now.

**Comment by jgriffitts** [comment]
Oops, I see that this issue has been discussed and resolved in the unreleased version 2.04. I had not found this before posting. Please feel free to delete this issue.
